set-option -g focus-events on

# Sätt standard-term
set -g default-terminal "tmux-256color"

# Aktivera RGB (True Color) stöd
# Detta är den kritiska raden för att slippa färgskiftningar
set -as terminal-features ",xterm-256color:RGB"

# Gör så att escape-sequences (som färgbyten) går snabbare
set -sg escape-time 10
